# Generated by Django 4.1.7 on 2023-03-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_boommark_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='update',
            new_name='updated',
        ),
    ]
